create database project_resturant;
show databases;
use project_resturant;

CREATE TABLE menu_items(
Menu_Item_Id INT,
Item_Name VARCHAR(100),
Category VARCHAR(100),
Price DECIMAL(10,2)
);

CREATE TABLE order_details(
Order_Details_Id INT,
Order_Id INT,
Order_Date Date,
Order_Time Time,
Item_Id INT 
);

select*from menu_items;
select*from order_details;

-- 1 what are the top 5 most sold menu items
select menu_items.item_name,count(order_details.order_id) as order_sold
from order_details
join menu_items
on order_details.item_id = menu_items.menu_item_id
group by menu_items.item_name
order by order_sold desc limit 5;

-- 2 what is the total revenue generated
select sum(menu_items.price*order_details.order_id) as total_revenue
from menu_items join order_details
on order_details.item_id = menu_items.menu_item_id;

-- 3 what is the average price of an item in each category
select category, avg(menu_items.price) as avg_price
from menu_items
group by category
order by avg_price desc;

-- 4 what is the total revenue generated by each food category
select menu_items.category, sum(menu_items.price) as total_revenue
from order_details
join menu_items
on order_details.item_id=menu_items.menu_item_id
group by menu_items.category
order by total_revenue desc;

-- 5 how many orders were placed on a specific month
select month(order_details.order_date) as months,count( distinct order_details.order_id) 
from order_details
group by months
order by months desc;

-- 6 what is the most exp item on menu
select item_name,price
from menu_items
order by price desc limit 1;

-- 7 what are the most popular category
select menu_items.category, count(order_details.item_id) as total_orders
from order_details
join menu_items
on menu_items.menu_item_id = order_details.item_id
group by menu_items.category
order by total_orders desc limit 1;


-- 8 how many distinct menu items were sold in total
select count(distinct order_details.item_id) as distinct_items_sold
from order_details
join menu_items on menu_items.menu_item_id = order_details.item_id;


-- 9 what is the avg order value
select avg(order_id) AS avg_order_value
from order_details;


-- 10 what is the items that has not been sold
select order_details.item_id,menu_items.item_name
from order_details
left join menu_items
on order_details.item_id = menu_items.menu_item_id
where order_details.item_id <> menu_items.menu_item_id;


-- 11 what is the daily total revenye (sales pr day)
select day(order_date) as order_day ,sum(menu_items.price) as daily_total_revenue
from menu_items join order_details
on order_details.item_id = menu_items.menu_item_id
group by day(order_date)
order by  order_day asc;


-- 12. : What is the peak hour for orders
select hour(order_details.order_time) as hours, count(order_details.order_id) as orders
from order_details
group by hours
order by orders desc limit 1;


-- 13. : What are the average daily orders?
select day(order_details.order_date), avg(order_id) as avg_order 
from order_details
group by day(order_date) 
order by day(order_date) asc;


-- 14. : What is the total revenue for the first quarter?
select quarter(order_date), sum(menu_items.price) as total_revenue
from menu_items
join order_details
on menu_items.menu_item_id = order_details.item_id
group by quarter(order_date)
order by total_revenue;


-- 15. : How many orders have more than one item?
select count(*) as orders
from (
select order_id from order_details
group by order_id having count(order_id)>1) as all_order;
     


-- 16. : What is the total number of unique customers 
-- (assuming each order_id is a unique customer)?

select count(distinct order_details.order_id) as no_of_customers
from order_details;


-- 17. : What is the average price of an item in the 'American' category?
select avg(menu_items.price) as  avg_american_item_price
from menu_items
where category = 'American';


-- 18. : Which item has the highest price in the 'Asian' category?
select item_name,price
from menu_items
where category = 'Asian'
order by  price desc limit 1;


-- 19. : What is the average number of items per order?
select order_id, count(item_id)as item_per_order
from order_details
 group by order_id;

-- 20. : How many menu items are there in each category?
select menu_items.category,count(item_name) as total_items
from menu_items
group by category
order by total_items desc;


-- 21. What is the total number of menu items sold?
select count(item_id) as total_menu_items_sold
from order_details;


-- 22. Which order has the highest total value?
select order_details.order_id, sum(menu_items.price) as total_order_value
from order_details
join menu_items
on menu_items.menu_item_id = order_details.item_id
group by order_details.order_id
order by total_order_value desc limit 1;



-- 23. What are the top 3 least sold menu items?

select menu_items.item_name,
count(order_details.item_id) as times_sold
from menu_items
 join order_details
on menu_items.menu_item_id = order_details.item_id
GROUP BY  menu_items.item_name
ORDER BY times_sold ASC
LIMIT 3;







